### PR TITLE
Lfric2lfric multi cpu

### LINKED ISSUE #192: lfric2lfric: run with multiple CPUs
### Are there any linked Issues or Pull Requests?

_No response_

### Brief description

At the moment, lfric2lfric can run in serial. When using more than one CPU, the application crashes because ranks other than zero do not read properly the partitioning for the source and the destination meshes. It is probably necessary to run lfric2lfric with more than one CPU when processing large meshes, both for memory and walltime limitations.

### Further details of the issue.

The problem was traced to the fact that the partitioning namelist was using an enumeration to identify the instance key member, which LFRic is not prepared to do. Substituting the enumeration by a simple string would solve the problem. In the metadata the accepted values of the instance key member can still be set.

### PR DESCRIPTION
**Pull request by ukmo-juan-castillo**
# PR Summary

Sci/Tech Reviewer: @mo-rickywong 
Code Reviewer: @TeranIvy 

Change the type of the partitioning key instance member for lfric2lfric, so that lfric2lfric can run with more than one CPU

Tagging Iva and Steve so they are aware of the suspect output from lfric2lfric on multiple CPUs
@TeranIvy , @stevemullerworth 

- closes #192 
- fixes #192 
-  blocks #275 #291 

## Code Quality Checklist

- [x] I have performed a self-review of my own code
- [x] My code follows the project's [style guidelines](https://metoffice.github.io/lfric_core/how_to_contribute/index.html#how-to-contribute-index)
- [x] Comments have been included that aid understanding and enhance the readability of the code
- [x] My changes generate no new warnings
- [x] All automated checks in the CI pipeline have completed successfully

## Testing

- [x] I have tested this change locally, using the LFRic Apps rose-stem suite
- [x] If any tests fail (rose-stem or CI) the reason is understood and acceptable (e.g. kgo changes)
- [x] I have added tests to cover new functionality as appropriate (e.g. system tests, unit tests, etc.)
- [ ] Any new tests have been assigned an appropriate amount of compute resource and have been allocated to an appropriate testing group (i.e. the developer tests are for jobs which use a small amount of compute resource and complete in a matter of minutes)

No other tests where performed, just modified existing tests so that the new functionality could be tested. Therefore, there were KGO changes that were addressed.

### trac.log

# Test Suite Results - lfric_apps - test_lfric2lfric_multi_CPU/run1

## Suite Information

| Item | Value |
| :--- | :--- |
| Suite Name | [test_lfric2lfric_multi_CPU/run1](https://cylchub/services/cylc-review/cycles/juan.m.castillo/?suite=test_lfric2lfric_multi_CPU%2Frun1) |
| Suite User | juan.m.castillo |
| Workflow Start | 2026-03-23T11:20:52 |
| Groups Run | all |

| Dependency | Reference | Main Like |
| :--- | :--- | :--- |
| casim | [MetOffice/casim@2026.03.2](https://github.com/MetOffice/casim/tree/2026.03.2) | True |
| jules | [MetOffice/jules@2026.03.2](https://github.com/MetOffice/jules/tree/2026.03.2) | True |
| lfric_apps | [ukmo-juan-castillo/lfric_apps@test_lfric2lfric_multi_CPU](https://github.com/ukmo-juan-castillo/lfric_apps/tree/test_lfric2lfric_multi_CPU) | False |
| lfric_core | [MetOffice/lfric_core@018e40c](https://github.com/MetOffice/lfric_core/tree/018e40c) | True |
| moci | [MetOffice/moci@2026.03.2](https://github.com/MetOffice/moci/tree/2026.03.2) | True |
| SimSys_Scripts | [MetOffice/SimSys_Scripts@4387949](https://github.com/MetOffice/SimSys_Scripts/tree/4387949) | True |
| socrates | [MetOffice/socrates@2026.03.2](https://github.com/MetOffice/socrates/tree/2026.03.2) | True |
| socrates-spectral | [MetOffice/socrates-spectral@2026.03.2](https://github.com/MetOffice/socrates-spectral/tree/2026.03.2) | True |
| ukca | [MetOffice/ukca@2026.03.2](https://github.com/MetOffice/ukca/tree/2026.03.2) | True |

## Task Information
:white_check_mark: succeeded tasks - 1512

## Security Considerations

- [x] I have reviewed my changes for potential security issues
- [x] Sensitive data is properly handled (if applicable)
- [x] Authentication and authorisation are properly implemented (if applicable)

## Performance Impact

- [x] Performance of the code has been considered and, if applicable, suitable performance measurements have been conducted

## AI Assistance and Attribution

- [ ] Some of the content of this change has been produced with the assistance of _Generative AI tool name_ (e.g., Met Office Github Copilot Enterprise, Github Copilot Personal, ChatGPT GPT-4, etc) and I have followed the [Simulation Systems AI policy](https://metoffice.github.io/simulation-systems/FurtherDetails/ai.html) (including attribution labels)

## Documentation

- [x] Where appropriate I have updated documentation related to this change and confirmed that it builds correctly

## PSyclone Approval

- [ ] If you have edited any PSyclone-related code (e.g. PSyKAl-lite, Kernel interface, optimisation scripts, LFRic data structure code) then please contact the [TCD Team](toolscollabdevteam@metoffice.gov.uk)

# Sci/Tech Review

- [x] I understand this area of code and the changes being added
- [ ] The proposed changes correspond to the pull request description
- [ ] Documentation is sufficient (do documentation papers need updating)
- [ ] Sufficient testing has been completed

Please detail **_how_** you tested the functionality? i.e. what modifications did you make to test it? doesn't seem like the rose-stem test should pass given the partitioning checks with the presence of inter-grid maps in the input mesh file.

KGOs changes are numerous and not all insignificant, please provide plots/evidence that output from multiple cpus is not significantly different from runs with multiple cpus (plots?).

SciTech Review: **Fail** Suspect results from runs with multiple CPUs. While this change may enable lfric2lfric to run with multiple CPUs, the output maybe **known** but not necessarily **good**

# Code Review

- [x] All dependencies have been resolved
- [ ] Related Issues have been properly linked and addressed
- [x] CLA compliance has been confirmed
- [x] Code quality standards have been met
- [x] Tests are adequate and have passed
- [ ] Documentation is complete and accurate
- [ ] Security considerations have been addressed
- [ ] Performance impact is acceptable

### CODE REVIEW

**Comment by ukmo-juan-castillo** [comment]
> You need to add yourself to the contributors file (alphabetical order)
> 
> This doesn't address the issue that there is no test-suite test that runs lfric2lfric on more than partition. Please create an issue to address it.
> 
> You say that you tested it to test that it works, how did you test it? As I recall you were using a input mesh file that had inter-grid maps. So did it not fail in the partitioning?
> 
> Please detail what you did to test you fix.

Added myself to the contributor list (added myself in a previous PR, but it has not been merged yet). I also fixed a detail in the new error message added to the code.

I modified the existing lfric2lfric rose stem tests, so that three of the jobs run with multiple CPUS: ral_seuk-C32_lam_MG, clim_gal9-C24_C12, and oasis_clim_gal9-C24_C12. That is the reason why there are KGO changes. I am afraid the results change slightly with the partitioning.

File: applications/lfric2lfric/source/initialisation/lfric2lfric_init_mesh.f90 [hunk 1]
```diff
@@ -136,11 +136,23 @@ subroutine init_mesh( configuration,           &
   ! Extract and check configuration variables
   !============================================================================
   ! Read partitioning namelist for source and destination meshes
+  if (.not. configuration%namelist_exists('partitioning', 'source')) then
+    write( log_scratch_space, '(A)' )                                     &
+         'Partitioning parameters for the source mesh were not found, '// &
+         'please specify a partitioning namelist with mesh_target=source.'
```
Comment (mo-rickywong) [inline applications/lfric2lfric/source/initialisation/lfric2lfric_init_mesh.f90]:
```suggestion
         'Source mesh partitioning namelist (partitioning:source) not found.'
```
If the code cannot find the required partitioning profile namelist, then that is all it should state, the code doesn't know why it can't be found, so it cannot suggest a solution. For example, if this error message was given for Marks problem, he would have checked the namelist file which was not at fault. This message also would have to be updated if a different key instance member was used.

The Rose metadata is enough for the user to be able to check their configuration settings.

File: applications/lfric2lfric/source/initialisation/lfric2lfric_init_mesh.f90 [hunk 2]
```diff
@@ -136,11 +136,23 @@ subroutine init_mesh( configuration,           &
...
+    call log_event(log_scratch_space, log_level_error)
+  end if
   src_partitioning_nml  => configuration%get_namelist('partitioning', &
                                                       'source')
   call src_partitioning_nml%get_value( 'generate_inner_halos', &
                                         generate_inner_halos(src) )
 
+  if (.not. configuration%namelist_exists('partitioning', 'destination')) then
+    write( log_scratch_space, '(A)' )                                     &
+         'Partitioning parameters for the source mesh were not found, '// &
```
Comment (mo-rickywong) [inline applications/lfric2lfric/source/initialisation/lfric2lfric_init_mesh.f90]:
```suggestion
         'Destination mesh partitioning namelist (partitioning:destination) not found.'
```
As before, the code doesn't know why the namelist is not found. Also the error message still referred to the source mesh.

**Comment by ukmo-juan-castillo** [comment]
Thank you for the proposed changes, they make the code clearer.

The issue wil the inter-grid maps will affect tests regridding from a global to a regional mesh, and will be the purpose of a different issue. That is the reason why the added multi CPU tests in this issue are global to global and regional to regional.

I looked at the differences in timing between tests with single and multiple CPUs, and although the multiple CPU tests were slightly faster, the tests run so quickly that it is difficult to draw conclusions about performance. I recommend 'real case' tests as the ones Mark is doing to properly assess performance.

After that I looked at differences in results with the nctools. In the global to global test, the differences in the output comes from the longitude and latitude of grid faces and nodes, not from the processed fields. In the regional to regional tests, there are differences in the longitude and latitude of grid faces only, and also in some of the 2D fields defined as (vertical coordinate, horizontal grid). I will try to change these variables to 1D fields to see if there are any changes in results, and prepare some plots.

**Comment by mo-rickywong** [comment]
I wouldn't be concerned about speed at this juncture, My comments where based of the KGO differences and attribution of them. You haven't shown what the 1 CPU Oasis regridded method produces or is that not possible?

If the differences are in the long/lats please provide example magnitudes? or the differences?

**Comment by ukmo-juan-castillo** [comment]
> I wouldn't be concerned about speed at this juncture, My comments where based of the KGO differences and attribution of them. You haven't shown what the 1 CPU Oasis regridded method produces or is that not possible?
> 
> If the differences are in the long/lats please provide example magnitudes? or the differences?

We looked in the past that the map and the oasis method gave the same results with one CPU, and this is still true although I did not include the plot. We find the same here with 4 CPUs.

I obtain lon/lat differences if I use ncdiff to generate the differences, but when I look at the actual longitude and latitude values in the lfric2lfric output using 1 or multiple CPUs, they are actually the same. I do not know why ncdiff behaves like this.

**Comment by ukmo-juan-castillo** [comment]
> No, that's not it, have you used nccmp? I want to see the differences in the lat lon values in the output. and similarly in the global mesh files you are using as input.

So far I only used ncdiff. Differences with nccmp are, for the regional model:

Variable               Group  Count          Sum      AbsSum           Min          Max       Range         Mean      StdDev
checkpoint_Wtheta      /          1           -1           1            -1           -1           0           -1           0
checkpoint_W3          /          1 -1.11253e+09 1.11253e+09  -1.11253e+09 -1.11253e+09           0 -1.11253e+09           0
checkpoint_W2          /          1 -1.11253e+09 1.11253e+09  -1.11253e+09 -1.11253e+09           0 -1.11253e+09           0
checkpoint_W2_node_x   /     220544            0      145292      -1.98049      2.10612      4.0866            0    0.830915
checkpoint_W2_node_y   /     220544            0      103486     -0.705284     0.823914      1.5292            0    0.500886
Mesh2d                 /          1 -1.11253e+09 1.11253e+09  -1.11253e+09 -1.11253e+09           0 -1.11253e+09           0
Mesh2d_edge_nodes      /        192            0         192            -1            1           2            0     1.00261
wvar                   /      72704   0.00111539     6164.43      -2.45019      2.51847     4.96866  1.53416e-08    0.228017
leaf_area_index        /       5062         -inf         inf -1.79769e+308 1.79769e+308         inf         -inf        -nan
canopy_height          /       5061         -inf         inf -1.79769e+308 1.79769e+308         inf         -inf        -nan
tile_fraction          /       8897  0.000115625     1078.55     -0.855488      0.84902     1.70451  1.29959e-08    0.197484
tile_temperature       /      11256      -407068 1.40123e+12  -8.05307e+08  8.05307e+08 1.61061e+09     -36.1645 2.25407e+08
tile_lw_grey_albedo    /      11236  5.60377e-05     106.052         -0.09        0.085       0.175  4.98733e-09   0.0226482
screen_temperature     /      11226       110413 2.78958e+12  -1.07374e+09  1.07374e+09 2.14748e+09      9.83549 3.77404e+08
tile_canopy_water      /       9365      -407067 1.40123e+12  -8.05307e+08  8.05307e+08 1.61061e+09     -43.4669 2.47121e+08
area_fraction          /      26938  0.000525767     1797.66            -1     0.770616     1.77062  1.95177e-08     0.14259
bulk_fraction          /      26938  0.000525767     1797.66            -1     0.770616     1.77062  1.95177e-08     0.14259
liquid_fraction        /      11801  5.13399e-05     350.829     -0.502809     0.398375    0.901184  4.35047e-09   0.0646092
frozen_fraction        /      21595  0.000474351     1458.08            -1     0.770616     1.77062  2.19658e-08    0.152085
ozone                  /      72663  4.37992e-08   0.0186999  -4.04532e-06   3.2943e-06 7.33962e-06  6.02771e-13  7.1005e-07
lw_up_tile_rts         /      11256    0.0784516      967019      -369.663      384.016     753.679  6.96976e-06     128.317
lw_heating_rate_rts    /      72704 -4.18205e-07    0.915891  -0.000222405  0.000283027 0.000505432 -5.75217e-12  2.5105e-05
lw_up_tile_rtsi        /      11256    0.0238005      342151      -130.928      136.271     267.199  2.11447e-06     45.6822
sw_heating_rate_rtsi   /       4370       12.559 4.56587e+07  -1.25056e+06  1.25056e+06 2.50113e+06    0.0028739      107275
lw_heating_rate_rtsi   /      72704        12.57 4.56463e+07  -1.25092e+06  1.25092e+06 2.50184e+06  0.000172892     26292.5
tile_snow_mass         /       5531      -407097 1.40127e+12  -8.05307e+08  8.05343e+08 1.61065e+09     -73.6029 3.21573e+08
tile_snow_rgrain       /      11195      -407067 1.40123e+12  -8.05307e+08  8.05307e+08 1.61061e+09     -36.3615 2.26021e+08
n_snow_layers          /       4487      -407067 1.40123e+12  -8.05307e+08  8.05307e+08 1.61061e+09     -90.7215 3.57035e+08
snow_depth             /       4487      -407067 1.40123e+12  -8.05307e+08  8.05307e+08 1.61061e+09     -90.7215 3.57035e+08
snowpack_density       /      11195      -407067 1.40123e+12  -8.05307e+08  8.05307e+08 1.61061e+09     -36.3615 2.26021e+08
snow_under_canopy      /       4487      -407067 1.40123e+12  -8.05307e+08  8.05307e+08 1.61061e+09     -90.7215 3.57035e+08
snow_layer_thickness   /      14576      -304125 4.77815e+12  -1.07374e+09  8.05307e+08 1.87905e+09     -20.8648 3.79038e+08
snow_layer_ice_mass    /      17515      -304091 4.77816e+12  -1.07378e+09  8.05343e+08 1.87912e+09     -17.3617 3.45777e+08
snow_layer_liq_mass    /      14576      -304125 4.77815e+12  -1.07374e+09  8.05307e+08 1.87905e+09     -20.8648 3.79038e+08
snow_layer_temp        /      27641      -304125 4.77815e+12  -1.07374e+09  8.05307e+08 1.87905e+09     -11.0027 2.75245e+08
snow_layer_rgrain      /      27641      -304125 4.77815e+12  -1.07374e+09  8.05307e+08 1.87905e+09     -11.0027 2.75244e+08
soil_temperature       /       4008     -1404.61 3.11385e+11  -1.07374e+09  1.07374e+09 2.14748e+09    -0.350451 2.01508e+08
soil_moisture          /       3944   -0.0488899      334394      -894.919      764.066     1658.98  -1.2396e-05     176.294
unfrozen_soil_moisture /       3944 -1.12559e-05     340.285     -0.965407     0.823503     1.78891 -2.85394e-09     0.16016

and for the global model:

Variable          Group Count          Sum      AbsSum          Min          Max Range         Mean  StdDev
checkpoint_W3     /         1 -1.10792e+09 1.10792e+09 -1.10792e+09 -1.10792e+09     0 -1.10792e+09       0
Mesh2d            /         1 -1.10792e+09 1.10792e+09 -1.10792e+09 -1.10792e+09     0 -1.10792e+09       0
Mesh2d_edge_nodes /       576            0       19244        -1867         1867  3734            0 173.939

**Comment by ukmo-juan-castillo** [comment]
> > > ### Global2Global differences between 1xCPU and 6xCPU
> > > ```
> > > * The edge node differences here are the same connectivity, though the orientation is transposed. This has been seen before as coming up with differences, although nothing as far as I know uses this connectivity (though I could be wrong).
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > image
> > > ```
> > > * Other differences appear to be with the id number of the field (I think), though I don't know how these are determined by the code that writes to file.
> > > ```
> > > image
> > > ### The Regional to Regional differences between 1xCPU and 4xCPU
> > > ```
> > > * Fields don't match, I think you posted the wrong files.
> > > ```
> > > **Note** you posted output for **run_lfric2lfric_ral_seuk-C32_lam_MG_azspice_gnu_fast-debug-64bit**. Though as we know the presence of intergrid maps will trigger checks that cause this to fail. So what if anything was done to get this to run? if this has been modified, I'd need to know.
> > 
> > 
> > I have updated the paths to the output files, sorry for the mistake.
> > I have not changed anything to be able to run using the multi grid. The only thing that is needed, I believe, is using a number of CPUs that divides the number of grid cells in each of the grids. I will open a new issue to deal with multigrids.
> 
> Your branch has set **_ral_seuk-C32_lam_MG_** to run with 4 cpus and changes the KGOS, but you have not posted the output. That is what I'm referring to in the previous message.
> 
> Thank you for the updated post, though there is still the missing output for the **_oasisi_clim_gal9-C24_C12_** runs

The output location for **_ral_seuk-C32_lam_MG_** with 4 cpus is described above: /home/users/juan.m.castillo/cylc-run/lfric2lfric_multi_CPU/run1/work/1/run_lfric2lfric_ral_seuk-C32_lam_MG_azspice_gnu_fast-debug-64bit/lfric_checkpoint_write.nc. I did not sent the output for the oasis equivalent because there are not relevant differences between the map and the oasis method: I think the results were the same within 1E-6 precision.

File: rose-stem/site/common/lfric2lfric/tasks_lfric2lfric.cylc [hunk 3]
```diff
@@ -94,6 +96,7 @@
         "src_mesh": "C24_C12",
         "src_name": "C12",
         "src_type": "global",
+        "mpi_parts": 6,
     }) %}
```
Comment (mo-rickywong) [inline rose-stem/site/common/lfric2lfric/tasks_lfric2lfric.cylc]: Revert

**Comment by ukmo-juan-castillo** [comment]
I updated as suggested by the reviewer, run again all rose stem tests, and updated trac.log in the PR description.
